name: "Linting"
on: [push]

jobs:
  lint_bot:
    runs-on: ubuntu-latest
    name: "Linting for Telegram Bot"

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      - name: Checkout the Code
        uses: actions/checkout@v3

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 for Telegram Bot
        run: flake8
        working-directory: ./bot/
